/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.devry.ecsproject.PresentationLayer;

import com.devry.ecsproject.BusinessLayer.EmployeeGUI;
import com.devry.ecsproject.BusinessLayer.EquipmentGUI;
import com.devry.ecsproject.BusinessLayer.ReportsGUI;

/**
 *
 * @author Jordan
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    /**
     * Creates new form LoginGUI_New
     */
    public MainGUI() {
        // initializer for MainGUI 
        initComponents();
        
        
        // set window to center of screen
        this.setLocationRelativeTo(null);

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupEquipmentTransaction = new javax.swing.ButtonGroup();
        tabPaneUIOptions = new javax.swing.JTabbedPane();
        pnlLoginGUI = new javax.swing.JPanel();
        pnlLoginBoxes = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblEmpId = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblLoginError = new javax.swing.JLabel();
        textEmpId = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        mnbMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPaneUIOptions.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pnlLoginGUI.setBackground(new java.awt.Color(204, 204, 204));
        pnlLoginGUI.setForeground(new java.awt.Color(153, 255, 0));
        pnlLoginGUI.setMinimumSize(new java.awt.Dimension(600, 328));
        pnlLoginGUI.setPreferredSize(new java.awt.Dimension(600, 328));

        pnlLoginBoxes.setBackground(new java.awt.Color(204, 204, 204));

        lblTitle.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("GB Manufacturing");
        lblTitle.setMaximumSize(new java.awt.Dimension(160, 25));
        lblTitle.setMinimumSize(new java.awt.Dimension(160, 25));
        lblTitle.setPreferredSize(new java.awt.Dimension(160, 25));

        lblEmpId.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblEmpId.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpId.setText("Employee ID:");
        lblEmpId.setMaximumSize(new java.awt.Dimension(160, 25));
        lblEmpId.setMinimumSize(new java.awt.Dimension(160, 25));
        lblEmpId.setPreferredSize(new java.awt.Dimension(160, 25));

        lblEmail.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email:");
        lblEmail.setMaximumSize(new java.awt.Dimension(160, 25));
        lblEmail.setMinimumSize(new java.awt.Dimension(160, 25));
        lblEmail.setPreferredSize(new java.awt.Dimension(160, 25));

        btnLogin.setText("Log In");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblLoginError.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(51, 51, 51));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginError.setText("Login Error");
        lblLoginError.setMaximumSize(new java.awt.Dimension(160, 25));
        lblLoginError.setMinimumSize(new java.awt.Dimension(160, 25));
        lblLoginError.setPreferredSize(new java.awt.Dimension(160, 25));

        javax.swing.GroupLayout pnlLoginBoxesLayout = new javax.swing.GroupLayout(pnlLoginBoxes);
        pnlLoginBoxes.setLayout(pnlLoginBoxesLayout);
        pnlLoginBoxesLayout.setHorizontalGroup(
            pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                        .addComponent(lblEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginBoxesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                .addGroup(pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginBoxesLayout.setVerticalGroup(
            pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlLoginGUILayout = new javax.swing.GroupLayout(pnlLoginGUI);
        pnlLoginGUI.setLayout(pnlLoginGUILayout);
        pnlLoginGUILayout.setHorizontalGroup(
            pnlLoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginGUILayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pnlLoginBoxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(217, 217, 217))
        );
        pnlLoginGUILayout.setVerticalGroup(
            pnlLoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoginBoxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        tabPaneUIOptions.addTab("User Login  ", pnlLoginGUI);

        mnbMain.setBackground(new java.awt.Color(51, 51, 51));
        mnbMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnbMain.setName(""); // NOI18N
        mnbMain.setOpaque(true);

        mnuFile.setText("File");
        mnuFile.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mnuFile.setOpaque(true);

        mniExit.setText("Exit");
        mniExit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mniExit.addActionListener(this::mniExitActionPerformed);
        mnuFile.add(mniExit);

        mnbMain.add(mnuFile);

        setJMenuBar(mnbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPaneUIOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPaneUIOptions)
        );

        tabPaneUIOptions.getAccessibleContext().setAccessibleName("TabbedPane");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    } // end of main
    
    
    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // exit button in menu clicked
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // button on screen clicked

        // get input from boxes
        String inputName = "Unknown";
        int inputId = 0;
        
        // TODO
        // validate inputs
        // check name is not empty
        // check id is not empty
        
        // verify user exists in database
        verifyUser(inputName, inputId); // TODO
        
        // check user access level in order to show proper UI options
        // Equipment Manager gets "Equipment" Tab and so forth
        // .setVisible() on the panels?
        
        // load proper UI tabs into Main UI Frame
        tabPaneUIOptions.addTab("Equipment", new EquipmentGUI());
        
        tabPaneUIOptions.addTab("Supervision", new EmployeeGUI());

        tabPaneUIOptions.addTab("Reports", new ReportsGUI());

        
        
        
        
    }//GEN-LAST:event_btnLoginActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupEquipmentTransaction;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuBar mnbMain;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JPanel pnlLoginBoxes;
    private javax.swing.JPanel pnlLoginGUI;
    private javax.swing.JTabbedPane tabPaneUIOptions;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEmpId;
    // End of variables declaration//GEN-END:variables

    
    
    
    private boolean verifyUser(String inputName, int inputId) {
        // TODO check user against active users in database
        // return boolean for verification
        return false;
    } // end of verifyUser
    
    
    
} // end of MainGUI
