/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.devry.ecsproject.PresentationLayer;

/**
 *
 * @author Jordan
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    /**
     * Creates new form LoginGUI_New
     */
    public MainGUI() {
        // initializer for MainGUI 
        initComponents();
        
        // set window to center of screen
        this.setLocationRelativeTo(null);

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupEquipmentTransaction = new javax.swing.ButtonGroup();
        tabPaneUIOptions = new javax.swing.JTabbedPane();
        pnlLoginGUI = new javax.swing.JPanel();
        pnlLoginBoxes = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblEmpId = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblLoginError = new javax.swing.JLabel();
        textEmpId = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        pnlEquipment = new javax.swing.JPanel();
        pnlRecords = new javax.swing.JPanel();
        textEmployeeID = new javax.swing.JTextField();
        textEquipmentID = new javax.swing.JTextField();
        lblEquipmentID = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        pnlTransaction = new javax.swing.JPanel();
        rdoBtnCheckin = new javax.swing.JRadioButton();
        rdoBtnCheckout = new javax.swing.JRadioButton();
        lblTransactionType = new javax.swing.JLabel();
        checkDamaged = new javax.swing.JCheckBox();
        btnSubmitEquipmentTransaction = new javax.swing.JButton();
        pnlEmployees = new javax.swing.JPanel();
        pnlEmployeeOptions = new javax.swing.JPanel();
        tabPaneEmployeeSupervision = new javax.swing.JTabbedPane();
        panelViewEmployee = new javax.swing.JPanel();
        pnlViewEmployeeInput = new javax.swing.JPanel();
        lblViewEmployeeID = new javax.swing.JLabel();
        inputIDViewEmployee = new javax.swing.JTextField();
        btnViewEmplyoeeSubmit = new javax.swing.JButton();
        lblViewEmployeeError = new javax.swing.JLabel();
        pnlViewEmployeeResults = new javax.swing.JPanel();
        lblViewEmployeeName = new javax.swing.JLabel();
        lblViewEmployeeEmail = new javax.swing.JLabel();
        lblViewEmployeeDate = new javax.swing.JLabel();
        lblViewEmployeeRole = new javax.swing.JLabel();
        lblViewEmployeeDepartment = new javax.swing.JLabel();
        lblViewEmployeeAccess = new javax.swing.JLabel();
        textViewEmployeeName = new javax.swing.JTextField();
        textViewEmployeeEmail = new javax.swing.JTextField();
        textViewEmployeeDate = new javax.swing.JTextField();
        textViewEmployeeRole = new javax.swing.JTextField();
        textViewEmployeeDepartment = new javax.swing.JTextField();
        textViewEmployeeAccess = new javax.swing.JTextField();
        panelHireEmployee = new javax.swing.JPanel();
        pnlHireEmployee = new javax.swing.JPanel();
        lblHireEmployeeName = new javax.swing.JLabel();
        lblHireEmployeeEmail = new javax.swing.JLabel();
        lblHireEmployeeRole = new javax.swing.JLabel();
        lblHireEmployeeDepartment = new javax.swing.JLabel();
        textHireEmployeeDepartment = new javax.swing.JTextField();
        textHireEmployeeRole = new javax.swing.JTextField();
        textHireEmployeeEmail = new javax.swing.JTextField();
        textHireEmployeeName = new javax.swing.JTextField();
        lblHireEmployeeAccess = new javax.swing.JLabel();
        textHireEmployeeAccess = new javax.swing.JTextField();
        btnHireEmployeeSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHireEmployeeResult = new javax.swing.JTextArea();
        panelTerminateEmployee = new javax.swing.JPanel();
        pnlReports = new javax.swing.JPanel();
        mnbMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPaneUIOptions.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pnlLoginGUI.setBackground(new java.awt.Color(204, 204, 204));
        pnlLoginGUI.setForeground(new java.awt.Color(153, 255, 0));
        pnlLoginGUI.setMinimumSize(new java.awt.Dimension(600, 328));
        pnlLoginGUI.setPreferredSize(new java.awt.Dimension(600, 328));

        pnlLoginBoxes.setBackground(new java.awt.Color(204, 204, 204));

        lblTitle.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("GB Manufacturing");
        lblTitle.setMaximumSize(new java.awt.Dimension(160, 25));
        lblTitle.setMinimumSize(new java.awt.Dimension(160, 25));
        lblTitle.setPreferredSize(new java.awt.Dimension(160, 25));

        lblEmpId.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblEmpId.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpId.setText("Employee ID:");
        lblEmpId.setMaximumSize(new java.awt.Dimension(160, 25));
        lblEmpId.setMinimumSize(new java.awt.Dimension(160, 25));
        lblEmpId.setPreferredSize(new java.awt.Dimension(160, 25));

        lblEmail.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email:");
        lblEmail.setMaximumSize(new java.awt.Dimension(160, 25));
        lblEmail.setMinimumSize(new java.awt.Dimension(160, 25));
        lblEmail.setPreferredSize(new java.awt.Dimension(160, 25));

        btnLogin.setText("Log In");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblLoginError.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(51, 51, 51));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginError.setText("Login Error");
        lblLoginError.setMaximumSize(new java.awt.Dimension(160, 25));
        lblLoginError.setMinimumSize(new java.awt.Dimension(160, 25));
        lblLoginError.setPreferredSize(new java.awt.Dimension(160, 25));

        javax.swing.GroupLayout pnlLoginBoxesLayout = new javax.swing.GroupLayout(pnlLoginBoxes);
        pnlLoginBoxes.setLayout(pnlLoginBoxesLayout);
        pnlLoginBoxesLayout.setHorizontalGroup(
            pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                        .addComponent(lblEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginBoxesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                .addGroup(pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginBoxesLayout.setVerticalGroup(
            pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginBoxesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlLoginBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlLoginGUILayout = new javax.swing.GroupLayout(pnlLoginGUI);
        pnlLoginGUI.setLayout(pnlLoginGUILayout);
        pnlLoginGUILayout.setHorizontalGroup(
            pnlLoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginGUILayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pnlLoginBoxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(217, 217, 217))
        );
        pnlLoginGUILayout.setVerticalGroup(
            pnlLoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoginBoxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        tabPaneUIOptions.addTab("User Login", pnlLoginGUI);

        pnlEquipment.setBackground(new java.awt.Color(204, 204, 204));

        pnlRecords.setBackground(new java.awt.Color(204, 204, 204));

        textEmployeeID.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        textEquipmentID.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        lblEquipmentID.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblEquipmentID.setForeground(new java.awt.Color(51, 51, 51));
        lblEquipmentID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEquipmentID.setText("Equipment Code:");
        lblEquipmentID.setMaximumSize(new java.awt.Dimension(160, 25));
        lblEquipmentID.setMinimumSize(new java.awt.Dimension(160, 25));
        lblEquipmentID.setPreferredSize(new java.awt.Dimension(160, 25));

        lblEmployeeID.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(51, 51, 51));
        lblEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmployeeID.setText("Employee's ID:");
        lblEmployeeID.setMaximumSize(new java.awt.Dimension(160, 25));
        lblEmployeeID.setMinimumSize(new java.awt.Dimension(160, 25));
        lblEmployeeID.setPreferredSize(new java.awt.Dimension(160, 25));

        lblTitle1.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Equipment Management");
        lblTitle1.setMaximumSize(new java.awt.Dimension(160, 25));
        lblTitle1.setMinimumSize(new java.awt.Dimension(160, 25));
        lblTitle1.setPreferredSize(new java.awt.Dimension(160, 25));

        javax.swing.GroupLayout pnlRecordsLayout = new javax.swing.GroupLayout(pnlRecords);
        pnlRecords.setLayout(pnlRecordsLayout);
        pnlRecordsLayout.setHorizontalGroup(
            pnlRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordsLayout.createSequentialGroup()
                .addGroup(pnlRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecordsLayout.createSequentialGroup()
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlRecordsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEquipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(textEquipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162))
            .addGroup(pnlRecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRecordsLayout.setVerticalGroup(
            pnlRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEquipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pnlTransaction.setBackground(new java.awt.Color(204, 204, 204));
        pnlTransaction.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGroupEquipmentTransaction.add(rdoBtnCheckin);
        rdoBtnCheckin.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        rdoBtnCheckin.setForeground(new java.awt.Color(51, 51, 51));
        rdoBtnCheckin.setText("Check In");
        rdoBtnCheckin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rdoBtnCheckin.addActionListener(this::rdoBtnCheckinActionPerformed);

        btnGroupEquipmentTransaction.add(rdoBtnCheckout);
        rdoBtnCheckout.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        rdoBtnCheckout.setForeground(new java.awt.Color(51, 51, 51));
        rdoBtnCheckout.setText("Check Out");
        rdoBtnCheckout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rdoBtnCheckout.addActionListener(this::rdoBtnCheckoutActionPerformed);

        lblTransactionType.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblTransactionType.setForeground(new java.awt.Color(51, 51, 51));
        lblTransactionType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTransactionType.setText("Transaction Info");
        lblTransactionType.setMaximumSize(new java.awt.Dimension(160, 25));
        lblTransactionType.setMinimumSize(new java.awt.Dimension(160, 25));
        lblTransactionType.setPreferredSize(new java.awt.Dimension(160, 25));

        checkDamaged.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        checkDamaged.setForeground(new java.awt.Color(51, 51, 51));
        checkDamaged.setText("Damaged ?");
        checkDamaged.setToolTipText("");
        checkDamaged.addActionListener(this::checkDamagedActionPerformed);

        btnSubmitEquipmentTransaction.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnSubmitEquipmentTransaction.setText("Submit");
        btnSubmitEquipmentTransaction.addActionListener(this::btnSubmitEquipmentTransactionActionPerformed);

        javax.swing.GroupLayout pnlTransactionLayout = new javax.swing.GroupLayout(pnlTransaction);
        pnlTransaction.setLayout(pnlTransactionLayout);
        pnlTransactionLayout.setHorizontalGroup(
            pnlTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransactionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoBtnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoBtnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSubmitEquipmentTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkDamaged, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlTransactionLayout.setVerticalGroup(
            pnlTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransactionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBtnCheckin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBtnCheckout)
                .addGap(58, 58, 58)
                .addComponent(checkDamaged)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnSubmitEquipmentTransaction)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlEquipmentLayout = new javax.swing.GroupLayout(pnlEquipment);
        pnlEquipment.setLayout(pnlEquipmentLayout);
        pnlEquipmentLayout.setHorizontalGroup(
            pnlEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipmentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pnlRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(pnlTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnlEquipmentLayout.setVerticalGroup(
            pnlEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipmentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tabPaneUIOptions.addTab("Equipment", pnlEquipment);

        pnlEmployees.setBackground(new java.awt.Color(204, 204, 204));
        pnlEmployees.setMaximumSize(new java.awt.Dimension(100, 32767));
        pnlEmployees.setPreferredSize(new java.awt.Dimension(100, 322));

        pnlEmployeeOptions.setBackground(new java.awt.Color(204, 204, 204));

        panelViewEmployee.setBackground(new java.awt.Color(204, 204, 204));

        pnlViewEmployeeInput.setBackground(new java.awt.Color(204, 204, 204));
        pnlViewEmployeeInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblViewEmployeeID.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeID.setForeground(new java.awt.Color(51, 51, 51));
        lblViewEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewEmployeeID.setText("Employee's ID:");
        lblViewEmployeeID.setMaximumSize(new java.awt.Dimension(160, 25));
        lblViewEmployeeID.setMinimumSize(new java.awt.Dimension(160, 25));
        lblViewEmployeeID.setPreferredSize(new java.awt.Dimension(160, 25));

        inputIDViewEmployee.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        btnViewEmplyoeeSubmit.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnViewEmplyoeeSubmit.setText("Submit");

        lblViewEmployeeError.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeError.setForeground(new java.awt.Color(51, 51, 51));
        lblViewEmployeeError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewEmployeeError.setText("Error");
        lblViewEmployeeError.setMaximumSize(new java.awt.Dimension(160, 25));
        lblViewEmployeeError.setMinimumSize(new java.awt.Dimension(160, 25));
        lblViewEmployeeError.setPreferredSize(new java.awt.Dimension(160, 25));

        javax.swing.GroupLayout pnlViewEmployeeInputLayout = new javax.swing.GroupLayout(pnlViewEmployeeInput);
        pnlViewEmployeeInput.setLayout(pnlViewEmployeeInputLayout);
        pnlViewEmployeeInputLayout.setHorizontalGroup(
            pnlViewEmployeeInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeeInputLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlViewEmployeeInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViewEmployeeInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewEmployeeInputLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewEmplyoeeSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12))
                        .addComponent(lblViewEmployeeError, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputIDViewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlViewEmployeeInputLayout.setVerticalGroup(
            pnlViewEmployeeInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeeInputLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblViewEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputIDViewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblViewEmployeeError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewEmplyoeeSubmit)
                .addGap(15, 15, 15))
        );

        btnViewEmplyoeeSubmit.getAccessibleContext().setAccessibleName("Submit Button");

        pnlViewEmployeeResults.setBackground(new java.awt.Color(204, 204, 204));
        pnlViewEmployeeResults.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblViewEmployeeName.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeName.setForeground(new java.awt.Color(51, 51, 51));
        lblViewEmployeeName.setText("Name");

        lblViewEmployeeEmail.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblViewEmployeeEmail.setText("Email");

        lblViewEmployeeDate.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeDate.setForeground(new java.awt.Color(51, 51, 51));
        lblViewEmployeeDate.setText("Hire Date");

        lblViewEmployeeRole.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeRole.setForeground(new java.awt.Color(51, 51, 51));
        lblViewEmployeeRole.setText("Role");

        lblViewEmployeeDepartment.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeDepartment.setForeground(new java.awt.Color(51, 51, 51));
        lblViewEmployeeDepartment.setText("Department");

        lblViewEmployeeAccess.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeAccess.setForeground(new java.awt.Color(51, 51, 51));
        lblViewEmployeeAccess.setText("Access Level");

        textViewEmployeeName.setEditable(false);
        textViewEmployeeName.setBackground(new java.awt.Color(225, 225, 225));
        textViewEmployeeName.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeName.setText("John Doe");
        textViewEmployeeName.setFocusable(false);

        textViewEmployeeEmail.setEditable(false);
        textViewEmployeeEmail.setBackground(new java.awt.Color(225, 225, 225));
        textViewEmployeeEmail.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeEmail.setText("jdoe555@email.com");
        textViewEmployeeEmail.setFocusable(false);

        textViewEmployeeDate.setEditable(false);
        textViewEmployeeDate.setBackground(new java.awt.Color(225, 225, 225));
        textViewEmployeeDate.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeDate.setText("12-31-1999");
        textViewEmployeeDate.setFocusable(false);

        textViewEmployeeRole.setEditable(false);
        textViewEmployeeRole.setBackground(new java.awt.Color(225, 225, 225));
        textViewEmployeeRole.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeRole.setText("Worker");
        textViewEmployeeRole.setFocusable(false);

        textViewEmployeeDepartment.setEditable(false);
        textViewEmployeeDepartment.setBackground(new java.awt.Color(225, 225, 225));
        textViewEmployeeDepartment.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeDepartment.setText("Maintenance");
        textViewEmployeeDepartment.setFocusable(false);

        textViewEmployeeAccess.setEditable(false);
        textViewEmployeeAccess.setBackground(new java.awt.Color(225, 225, 225));
        textViewEmployeeAccess.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeAccess.setText("1");
        textViewEmployeeAccess.setFocusable(false);

        javax.swing.GroupLayout pnlViewEmployeeResultsLayout = new javax.swing.GroupLayout(pnlViewEmployeeResults);
        pnlViewEmployeeResults.setLayout(pnlViewEmployeeResultsLayout);
        pnlViewEmployeeResultsLayout.setHorizontalGroup(
            pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeeResultsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblViewEmployeeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeDate, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeRole, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeAccess, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textViewEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlViewEmployeeResultsLayout.setVerticalGroup(
            pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeeResultsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewEmployeeName)
                    .addComponent(textViewEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewEmployeeEmail)
                    .addComponent(textViewEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textViewEmployeeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEmployeeDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textViewEmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEmployeeRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textViewEmployeeDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEmployeeDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewEmployeeAccess)
                    .addComponent(textViewEmployeeAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelViewEmployeeLayout = new javax.swing.GroupLayout(panelViewEmployee);
        panelViewEmployee.setLayout(panelViewEmployeeLayout);
        panelViewEmployeeLayout.setHorizontalGroup(
            panelViewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewEmployeeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlViewEmployeeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlViewEmployeeResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelViewEmployeeLayout.setVerticalGroup(
            panelViewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewEmployeeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlViewEmployeeResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlViewEmployeeInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneEmployeeSupervision.addTab("View Employee", panelViewEmployee);

        panelHireEmployee.setBackground(new java.awt.Color(204, 204, 204));

        pnlHireEmployee.setBackground(new java.awt.Color(204, 204, 204));
        pnlHireEmployee.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblHireEmployeeName.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeName.setForeground(new java.awt.Color(51, 51, 51));
        lblHireEmployeeName.setText("Name");

        lblHireEmployeeEmail.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblHireEmployeeEmail.setText("Email");

        lblHireEmployeeRole.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeRole.setForeground(new java.awt.Color(51, 51, 51));
        lblHireEmployeeRole.setText("Role");

        lblHireEmployeeDepartment.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeDepartment.setForeground(new java.awt.Color(51, 51, 51));
        lblHireEmployeeDepartment.setText("Department");

        textHireEmployeeDepartment.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        textHireEmployeeRole.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        textHireEmployeeEmail.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        textHireEmployeeName.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        lblHireEmployeeAccess.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeAccess.setForeground(new java.awt.Color(51, 51, 51));
        lblHireEmployeeAccess.setText("Access Level");

        textHireEmployeeAccess.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        btnHireEmployeeSubmit.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnHireEmployeeSubmit.setText("Submit");

        javax.swing.GroupLayout pnlHireEmployeeLayout = new javax.swing.GroupLayout(pnlHireEmployee);
        pnlHireEmployee.setLayout(pnlHireEmployeeLayout);
        pnlHireEmployeeLayout.setHorizontalGroup(
            pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHireEmployeeLayout.createSequentialGroup()
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHireEmployeeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHireEmployeeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHireEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHireEmployeeRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHireEmployeeDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHireEmployeeAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textHireEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHireEmployeeAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHireEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHireEmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHireEmployeeDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHireEmployeeLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnHireEmployeeSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlHireEmployeeLayout.setVerticalGroup(
            pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHireEmployeeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHireEmployeeName)
                    .addComponent(textHireEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHireEmployeeEmail)
                    .addComponent(textHireEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHireEmployeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHireEmployeeRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHireEmployeeDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHireEmployeeDepartment))
                .addGap(11, 11, 11)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHireEmployeeAccess)
                    .addComponent(textHireEmployeeAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnHireEmployeeSubmit)
                .addGap(21, 21, 21))
        );

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHireEmployeeResult.setEditable(false);
        txtHireEmployeeResult.setBackground(new java.awt.Color(204, 204, 204));
        txtHireEmployeeResult.setColumns(20);
        txtHireEmployeeResult.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        txtHireEmployeeResult.setForeground(new java.awt.Color(51, 51, 51));
        txtHireEmployeeResult.setLineWrap(true);
        txtHireEmployeeResult.setRows(5);
        txtHireEmployeeResult.setText("Employee Added to DB\n\nID: 00001\nName: John Doe\nEmail: jdoe@email.com\nHire Date: 12-31-1999\nRole: Worker\nDepartment: Maintenance\nAccess Level: 1");
        txtHireEmployeeResult.setBorder(null);
        txtHireEmployeeResult.setFocusable(false);
        jScrollPane1.setViewportView(txtHireEmployeeResult);

        javax.swing.GroupLayout panelHireEmployeeLayout = new javax.swing.GroupLayout(panelHireEmployee);
        panelHireEmployee.setLayout(panelHireEmployeeLayout);
        panelHireEmployeeLayout.setHorizontalGroup(
            panelHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHireEmployeeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlHireEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        panelHireEmployeeLayout.setVerticalGroup(
            panelHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHireEmployeeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelHireEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlHireEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneEmployeeSupervision.addTab("Hire Employee", panelHireEmployee);

        javax.swing.GroupLayout panelTerminateEmployeeLayout = new javax.swing.GroupLayout(panelTerminateEmployee);
        panelTerminateEmployee.setLayout(panelTerminateEmployeeLayout);
        panelTerminateEmployeeLayout.setHorizontalGroup(
            panelTerminateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTerminateEmployeeLayout.setVerticalGroup(
            panelTerminateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabPaneEmployeeSupervision.addTab("Terminate Employee", panelTerminateEmployee);

        javax.swing.GroupLayout pnlEmployeeOptionsLayout = new javax.swing.GroupLayout(pnlEmployeeOptions);
        pnlEmployeeOptions.setLayout(pnlEmployeeOptionsLayout);
        pnlEmployeeOptionsLayout.setHorizontalGroup(
            pnlEmployeeOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeOptionsLayout.createSequentialGroup()
                .addComponent(tabPaneEmployeeSupervision, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEmployeeOptionsLayout.setVerticalGroup(
            pnlEmployeeOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeOptionsLayout.createSequentialGroup()
                .addComponent(tabPaneEmployeeSupervision, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabPaneEmployeeSupervision.getAccessibleContext().setAccessibleName("Employee Supervision Tabs");

        javax.swing.GroupLayout pnlEmployeesLayout = new javax.swing.GroupLayout(pnlEmployees);
        pnlEmployees.setLayout(pnlEmployeesLayout);
        pnlEmployeesLayout.setHorizontalGroup(
            pnlEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmployeesLayout.createSequentialGroup()
                .addComponent(pnlEmployeeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 510, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlEmployeesLayout.setVerticalGroup(
            pnlEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEmployeeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 322, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        tabPaneUIOptions.addTab("Supervision", pnlEmployees);

        pnlReports.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        tabPaneUIOptions.addTab("Reports", pnlReports);

        mnbMain.setBackground(new java.awt.Color(51, 51, 51));
        mnbMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnbMain.setName(""); // NOI18N
        mnbMain.setOpaque(true);

        mnuFile.setText("File");
        mnuFile.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mnuFile.setOpaque(true);

        mniExit.setText("Exit");
        mniExit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mniExit.addActionListener(this::mniExitActionPerformed);
        mnuFile.add(mniExit);

        mnbMain.add(mnuFile);

        setJMenuBar(mnbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPaneUIOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPaneUIOptions)
        );

        tabPaneUIOptions.getAccessibleContext().setAccessibleName("TabbedPane");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    } // end of main
    
    
    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // exit button in menu clicked
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // button on screen clicked

        // get input from boxes
        String inputName = "Unknown";
        int inputId = 0;
        
        // TODO
        // validate inputs
        // check name is not empty
        // check id is not empty
        
        // verify user exists in database
        verifyUser(inputName, inputId); // TODO
        
        // check user access level in order to show proper UI options
        // Equipment Manager gets "Equipment" Tab and so forth
        // .setVisible() on the panels?
        
        // load proper UI tabs into Main UI Frame
        
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void rdoBtnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnCheckoutActionPerformed
        // TODO
        // verify equipment not checked out already
        // set transaction type to checkout
    }//GEN-LAST:event_rdoBtnCheckoutActionPerformed

    private void rdoBtnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnCheckinActionPerformed
        // TODO
        // verify equipment not checked in already
        // set transaction type to checkin
    }//GEN-LAST:event_rdoBtnCheckinActionPerformed

    private void checkDamagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDamagedActionPerformed
        // TODO
        // if checked, update record in db
    }//GEN-LAST:event_checkDamagedActionPerformed

    private void btnSubmitEquipmentTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitEquipmentTransactionActionPerformed
        // TODO
        // validate input boxes / buttons
        // create report for transaction
        // return report / id for report
    }//GEN-LAST:event_btnSubmitEquipmentTransactionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupEquipmentTransaction;
    private javax.swing.JButton btnHireEmployeeSubmit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSubmitEquipmentTransaction;
    private javax.swing.JButton btnViewEmplyoeeSubmit;
    private javax.swing.JCheckBox checkDamaged;
    private javax.swing.JTextField inputIDViewEmployee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEquipmentID;
    private javax.swing.JLabel lblHireEmployeeAccess;
    private javax.swing.JLabel lblHireEmployeeDepartment;
    private javax.swing.JLabel lblHireEmployeeEmail;
    private javax.swing.JLabel lblHireEmployeeName;
    private javax.swing.JLabel lblHireEmployeeRole;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTransactionType;
    private javax.swing.JLabel lblViewEmployeeAccess;
    private javax.swing.JLabel lblViewEmployeeDate;
    private javax.swing.JLabel lblViewEmployeeDepartment;
    private javax.swing.JLabel lblViewEmployeeEmail;
    private javax.swing.JLabel lblViewEmployeeError;
    private javax.swing.JLabel lblViewEmployeeID;
    private javax.swing.JLabel lblViewEmployeeName;
    private javax.swing.JLabel lblViewEmployeeRole;
    private javax.swing.JMenuBar mnbMain;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JPanel panelHireEmployee;
    private javax.swing.JPanel panelTerminateEmployee;
    private javax.swing.JPanel panelViewEmployee;
    private javax.swing.JPanel pnlEmployeeOptions;
    private javax.swing.JPanel pnlEmployees;
    private javax.swing.JPanel pnlEquipment;
    private javax.swing.JPanel pnlHireEmployee;
    private javax.swing.JPanel pnlLoginBoxes;
    private javax.swing.JPanel pnlLoginGUI;
    private javax.swing.JPanel pnlRecords;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlTransaction;
    private javax.swing.JPanel pnlViewEmployeeInput;
    private javax.swing.JPanel pnlViewEmployeeResults;
    private javax.swing.JRadioButton rdoBtnCheckin;
    private javax.swing.JRadioButton rdoBtnCheckout;
    private javax.swing.JTabbedPane tabPaneEmployeeSupervision;
    private javax.swing.JTabbedPane tabPaneUIOptions;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEmpId;
    private javax.swing.JTextField textEmployeeID;
    private javax.swing.JTextField textEquipmentID;
    private javax.swing.JTextField textHireEmployeeAccess;
    private javax.swing.JTextField textHireEmployeeDepartment;
    private javax.swing.JTextField textHireEmployeeEmail;
    private javax.swing.JTextField textHireEmployeeName;
    private javax.swing.JTextField textHireEmployeeRole;
    private javax.swing.JTextField textViewEmployeeAccess;
    private javax.swing.JTextField textViewEmployeeDate;
    private javax.swing.JTextField textViewEmployeeDepartment;
    private javax.swing.JTextField textViewEmployeeEmail;
    private javax.swing.JTextField textViewEmployeeName;
    private javax.swing.JTextField textViewEmployeeRole;
    private javax.swing.JTextArea txtHireEmployeeResult;
    // End of variables declaration//GEN-END:variables

    
    
    
    private boolean verifyUser(String inputName, int inputId) {
        // TODO check user against active users in database
        // return boolean for verification
        return false;
    } // end of verifyUser
    
    
    
} // end of MainGUI
