/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.devry.ecsproject.BusinessLayer;

import com.devry.ecsproject.DataLayer.Employee;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Jordan
 */
public class EmployeeGUI extends javax.swing.JPanel {
    
    private EmployeeGUIService employeeService;

    /**
     * Creates new form EmployeePanel
     */
    public EmployeeGUI() {
        initComponents();
        employeeService = new EmployeeGUIService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlEmployees = new JPanel();
        pnlEmployeeOptions = new JPanel();
        tabPaneEmployeeSupervision = new JTabbedPane();
        panelViewEmployee = new JPanel();
        pnlViewEmployeeInput = new JPanel();
        lblViewEmployeeID = new JLabel();
        inputIDViewEmployee = new JTextField();
        btnViewEmplyoeeSubmit = new JButton();
        lblViewEmployeeError = new JLabel();
        pnlViewEmployeeResults = new JPanel();
        lblViewEmployeeName = new JLabel();
        lblViewEmployeeEmail = new JLabel();
        lblViewEmployeeDate = new JLabel();
        lblViewEmployeeRole = new JLabel();
        lblViewEmployeeDepartment = new JLabel();
        lblViewEmployeeAccess = new JLabel();
        textViewEmployeeName = new JTextField();
        textViewEmployeeEmail = new JTextField();
        textViewEmployeeDate = new JTextField();
        textViewEmployeeRole = new JTextField();
        textViewEmployeeDepartment = new JTextField();
        textViewEmployeeAccess = new JTextField();
        panelHireEmployee = new JPanel();
        pnlHireEmployee = new JPanel();
        lblHireEmployeeName = new JLabel();
        lblHireEmployeeEmail = new JLabel();
        lblHireEmployeeRole = new JLabel();
        lblHireEmployeeDepartment = new JLabel();
        textHireEmployeeDepartment = new JTextField();
        textHireEmployeeRole = new JTextField();
        textHireEmployeeEmail = new JTextField();
        textHireEmployeeName = new JTextField();
        lblHireEmployeeAccess = new JLabel();
        textHireEmployeeAccess = new JTextField();
        btnHireEmployeeSubmit = new JButton();
        jScrollPane1 = new JScrollPane();
        txtHireEmployeeResult = new JTextArea();
        panelTerminateEmployee = new JPanel();
        pnlTerminateEmployeeInput = new JPanel();
        lblTerminateEmployeeID = new JLabel();
        inputIDTerminateEmployee = new JTextField();
        btnTerminateEmplyoeeView = new JButton();
        lblTerminateEmployeeError = new JLabel();
        pnlTerminateEmployeeResults = new JPanel();
        lblTerminateEmployeeName = new JLabel();
        lblTerminateEmployeeEmail = new JLabel();
        lblTerminateEmployeeDate = new JLabel();
        lblTerminateEmployeeRole = new JLabel();
        lblTerminateEmployeeDepartment = new JLabel();
        lblTerminateEmployeeAccess = new JLabel();
        textTerminateEmployeeName = new JTextField();
        textTerminateEmployeeEmail = new JTextField();
        textTerminateEmployeeDate = new JTextField();
        textTerminateEmployeeRole = new JTextField();
        textTerminateEmployeeDepartment = new JTextField();
        textTerminateEmployeeAccess = new JTextField();
        btnTerminateEmplyoeeSubmit = new JButton();

        pnlEmployees.setBackground(new Color(204, 204, 204));
        pnlEmployees.setMaximumSize(new Dimension(100, 32767));
        pnlEmployees.setPreferredSize(new Dimension(100, 322));

        pnlEmployeeOptions.setBackground(new Color(204, 204, 204));

        panelViewEmployee.setBackground(new Color(204, 204, 204));

        pnlViewEmployeeInput.setBackground(new Color(204, 204, 204));
        pnlViewEmployeeInput.setBorder(BorderFactory.createEtchedBorder());

        lblViewEmployeeID.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeID.setForeground(new Color(51, 51, 51));
        lblViewEmployeeID.setHorizontalAlignment(SwingConstants.CENTER);
        lblViewEmployeeID.setText("Employee's ID:");
        lblViewEmployeeID.setMaximumSize(new Dimension(160, 25));
        lblViewEmployeeID.setMinimumSize(new Dimension(160, 25));
        lblViewEmployeeID.setPreferredSize(new Dimension(160, 25));

        inputIDViewEmployee.setFont(new Font("Candara", 0, 12)); // NOI18N

        btnViewEmplyoeeSubmit.setFont(new Font("Candara", 0, 14)); // NOI18N
        btnViewEmplyoeeSubmit.setText("Submit");
        btnViewEmplyoeeSubmit.addActionListener(this::btnViewEmployeeSubmitActionPerformed);

        lblViewEmployeeError.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeError.setForeground(new Color(51, 51, 51));
        lblViewEmployeeError.setHorizontalAlignment(SwingConstants.CENTER);
        lblViewEmployeeError.setText("Error");
        lblViewEmployeeError.setMaximumSize(new Dimension(160, 25));
        lblViewEmployeeError.setMinimumSize(new Dimension(160, 25));
        lblViewEmployeeError.setPreferredSize(new Dimension(160, 25));

        GroupLayout pnlViewEmployeeInputLayout = new GroupLayout(pnlViewEmployeeInput);
        pnlViewEmployeeInput.setLayout(pnlViewEmployeeInputLayout);
        pnlViewEmployeeInputLayout.setHorizontalGroup(
            pnlViewEmployeeInputLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeeInputLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlViewEmployeeInputLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViewEmployeeInputLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, pnlViewEmployeeInputLayout.createSequentialGroup()
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 13, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewEmplyoeeSubmit, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12))
                        .addComponent(lblViewEmployeeError, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputIDViewEmployee, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEmployeeID, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlViewEmployeeInputLayout.setVerticalGroup(
            pnlViewEmployeeInputLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeeInputLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblViewEmployeeID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputIDViewEmployee, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(lblViewEmployeeError, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewEmplyoeeSubmit)
                .addContainerGap())
        );

        pnlViewEmployeeResults.setBackground(new Color(204, 204, 204));
        pnlViewEmployeeResults.setBorder(BorderFactory.createEtchedBorder());

        lblViewEmployeeName.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeName.setForeground(new Color(51, 51, 51));
        lblViewEmployeeName.setText("Name");

        lblViewEmployeeEmail.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeEmail.setForeground(new Color(51, 51, 51));
        lblViewEmployeeEmail.setText("Email");

        lblViewEmployeeDate.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeDate.setForeground(new Color(51, 51, 51));
        lblViewEmployeeDate.setText("Hire Date");

        lblViewEmployeeRole.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeRole.setForeground(new Color(51, 51, 51));
        lblViewEmployeeRole.setText("Role");

        lblViewEmployeeDepartment.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeDepartment.setForeground(new Color(51, 51, 51));
        lblViewEmployeeDepartment.setText("Department");

        lblViewEmployeeAccess.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblViewEmployeeAccess.setForeground(new Color(51, 51, 51));
        lblViewEmployeeAccess.setText("Access Level");

        textViewEmployeeName.setEditable(false);
        textViewEmployeeName.setBackground(new Color(225, 225, 225));
        textViewEmployeeName.setFont(new Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeName.setText("John Doe");
        textViewEmployeeName.setFocusable(false);

        textViewEmployeeEmail.setEditable(false);
        textViewEmployeeEmail.setBackground(new Color(225, 225, 225));
        textViewEmployeeEmail.setFont(new Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeEmail.setText("jdoe555@email.com");
        textViewEmployeeEmail.setFocusable(false);

        textViewEmployeeDate.setEditable(false);
        textViewEmployeeDate.setBackground(new Color(225, 225, 225));
        textViewEmployeeDate.setFont(new Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeDate.setText("12-31-1999");
        textViewEmployeeDate.setFocusable(false);

        textViewEmployeeRole.setEditable(false);
        textViewEmployeeRole.setBackground(new Color(225, 225, 225));
        textViewEmployeeRole.setFont(new Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeRole.setText("Worker");
        textViewEmployeeRole.setFocusable(false);

        textViewEmployeeDepartment.setEditable(false);
        textViewEmployeeDepartment.setBackground(new Color(225, 225, 225));
        textViewEmployeeDepartment.setFont(new Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeDepartment.setText("Maintenance");
        textViewEmployeeDepartment.setFocusable(false);

        textViewEmployeeAccess.setEditable(false);
        textViewEmployeeAccess.setBackground(new Color(225, 225, 225));
        textViewEmployeeAccess.setFont(new Font("Candara", 0, 12)); // NOI18N
        textViewEmployeeAccess.setText("1");
        textViewEmployeeAccess.setFocusable(false);

        GroupLayout pnlViewEmployeeResultsLayout = new GroupLayout(pnlViewEmployeeResults);
        pnlViewEmployeeResults.setLayout(pnlViewEmployeeResultsLayout);
        pnlViewEmployeeResultsLayout.setHorizontalGroup(
            pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeeResultsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblViewEmployeeEmail, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeDate, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeRole, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeDepartment, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblViewEmployeeAccess, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(textViewEmployeeName, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeEmail, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeDate, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeRole, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeDepartment, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                    .addComponent(textViewEmployeeAccess, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlViewEmployeeResultsLayout.setVerticalGroup(
            pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeeResultsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewEmployeeName)
                    .addComponent(textViewEmployeeName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewEmployeeEmail)
                    .addComponent(textViewEmployeeEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textViewEmployeeDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEmployeeDate))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textViewEmployeeRole, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEmployeeRole))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textViewEmployeeDepartment, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewEmployeeDepartment))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlViewEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewEmployeeAccess)
                    .addComponent(textViewEmployeeAccess, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout panelViewEmployeeLayout = new GroupLayout(panelViewEmployee);
        panelViewEmployee.setLayout(panelViewEmployeeLayout);
        panelViewEmployeeLayout.setHorizontalGroup(
            panelViewEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelViewEmployeeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnlViewEmployeeInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlViewEmployeeResults, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelViewEmployeeLayout.setVerticalGroup(
            panelViewEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelViewEmployeeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelViewEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlViewEmployeeResults, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlViewEmployeeInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tabPaneEmployeeSupervision.addTab("View Employee", panelViewEmployee);

        panelHireEmployee.setBackground(new Color(204, 204, 204));

        pnlHireEmployee.setBackground(new Color(204, 204, 204));
        pnlHireEmployee.setBorder(BorderFactory.createEtchedBorder());

        lblHireEmployeeName.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeName.setForeground(new Color(51, 51, 51));
        lblHireEmployeeName.setText("Name");

        lblHireEmployeeEmail.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeEmail.setForeground(new Color(51, 51, 51));
        lblHireEmployeeEmail.setText("Email");

        lblHireEmployeeRole.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeRole.setForeground(new Color(51, 51, 51));
        lblHireEmployeeRole.setText("Role");

        lblHireEmployeeDepartment.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeDepartment.setForeground(new Color(51, 51, 51));
        lblHireEmployeeDepartment.setText("Department");

        textHireEmployeeDepartment.setFont(new Font("Candara", 0, 12)); // NOI18N

        textHireEmployeeRole.setFont(new Font("Candara", 0, 12)); // NOI18N

        textHireEmployeeEmail.setFont(new Font("Candara", 0, 12)); // NOI18N

        textHireEmployeeName.setFont(new Font("Candara", 0, 12)); // NOI18N

        lblHireEmployeeAccess.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblHireEmployeeAccess.setForeground(new Color(51, 51, 51));
        lblHireEmployeeAccess.setText("Access Level");

        textHireEmployeeAccess.setFont(new Font("Candara", 0, 12)); // NOI18N

        btnHireEmployeeSubmit.setFont(new Font("Candara", 0, 14)); // NOI18N
        btnHireEmployeeSubmit.setText("Submit");
        btnHireEmployeeSubmit.addActionListener(this::btnHireEmployeeSubmitActionPerformed);

        GroupLayout pnlHireEmployeeLayout = new GroupLayout(pnlHireEmployee);
        pnlHireEmployee.setLayout(pnlHireEmployeeLayout);
        pnlHireEmployeeLayout.setHorizontalGroup(
            pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlHireEmployeeLayout.createSequentialGroup()
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHireEmployeeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHireEmployeeEmail, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHireEmployeeName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHireEmployeeRole, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHireEmployeeDepartment, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHireEmployeeAccess, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(textHireEmployeeName, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHireEmployeeAccess, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHireEmployeeEmail, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHireEmployeeRole, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHireEmployeeDepartment, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHireEmployeeLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnHireEmployeeSubmit, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlHireEmployeeLayout.setVerticalGroup(
            pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlHireEmployeeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHireEmployeeName)
                    .addComponent(textHireEmployeeName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHireEmployeeEmail)
                    .addComponent(textHireEmployeeEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textHireEmployeeRole, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHireEmployeeRole))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textHireEmployeeDepartment, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHireEmployeeDepartment))
                .addGap(11, 11, 11)
                .addGroup(pnlHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHireEmployeeAccess)
                    .addComponent(textHireEmployeeAccess, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnHireEmployeeSubmit)
                .addGap(21, 21, 21))
        );

        jScrollPane1.setBackground(new Color(204, 204, 204));
        jScrollPane1.setBorder(BorderFactory.createEtchedBorder());

        txtHireEmployeeResult.setEditable(false);
        txtHireEmployeeResult.setBackground(new Color(204, 204, 204));
        txtHireEmployeeResult.setColumns(20);
        txtHireEmployeeResult.setFont(new Font("Candara", 0, 12)); // NOI18N
        txtHireEmployeeResult.setForeground(new Color(51, 51, 51));
        txtHireEmployeeResult.setLineWrap(true);
        txtHireEmployeeResult.setRows(5);
        txtHireEmployeeResult.setText("Employee Added to DB\n\nID: 00001\nName: John Doe\nEmail: jdoe@email.com\nHire Date: 12-31-1999\nRole: Worker\nDepartment: Maintenance\nAccess Level: 1");
        txtHireEmployeeResult.setBorder(null);
        txtHireEmployeeResult.setFocusable(false);
        jScrollPane1.setViewportView(txtHireEmployeeResult);

        GroupLayout panelHireEmployeeLayout = new GroupLayout(panelHireEmployee);
        panelHireEmployee.setLayout(panelHireEmployeeLayout);
        panelHireEmployeeLayout.setHorizontalGroup(
            panelHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelHireEmployeeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlHireEmployee, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        panelHireEmployeeLayout.setVerticalGroup(
            panelHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelHireEmployeeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelHireEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlHireEmployee, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneEmployeeSupervision.addTab("Hire Employee", panelHireEmployee);

        panelTerminateEmployee.setBackground(new Color(204, 204, 204));

        pnlTerminateEmployeeInput.setBackground(new Color(204, 204, 204));
        pnlTerminateEmployeeInput.setBorder(BorderFactory.createEtchedBorder());

        lblTerminateEmployeeID.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblTerminateEmployeeID.setForeground(new Color(51, 51, 51));
        lblTerminateEmployeeID.setHorizontalAlignment(SwingConstants.CENTER);
        lblTerminateEmployeeID.setText("Employee's ID:");
        lblTerminateEmployeeID.setMaximumSize(new Dimension(160, 25));
        lblTerminateEmployeeID.setMinimumSize(new Dimension(160, 25));
        lblTerminateEmployeeID.setPreferredSize(new Dimension(160, 25));

        inputIDTerminateEmployee.setFont(new Font("Candara", 0, 12)); // NOI18N

        btnTerminateEmplyoeeView.setFont(new Font("Candara", 0, 14)); // NOI18N
        btnTerminateEmplyoeeView.setText("View");
        btnTerminateEmplyoeeView.addActionListener(this::btnTerminateEmployeeViewActionPerformed);

        lblTerminateEmployeeError.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblTerminateEmployeeError.setForeground(new Color(51, 51, 51));
        lblTerminateEmployeeError.setHorizontalAlignment(SwingConstants.CENTER);
        lblTerminateEmployeeError.setText("Error");
        lblTerminateEmployeeError.setMaximumSize(new Dimension(160, 25));
        lblTerminateEmployeeError.setMinimumSize(new Dimension(160, 25));
        lblTerminateEmployeeError.setPreferredSize(new Dimension(160, 25));

        GroupLayout pnlTerminateEmployeeInputLayout = new GroupLayout(pnlTerminateEmployeeInput);
        pnlTerminateEmployeeInput.setLayout(pnlTerminateEmployeeInputLayout);
        pnlTerminateEmployeeInputLayout.setHorizontalGroup(
            pnlTerminateEmployeeInputLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlTerminateEmployeeInputLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlTerminateEmployeeInputLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTerminateEmployeeInputLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, pnlTerminateEmployeeInputLayout.createSequentialGroup()
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 13, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTerminateEmplyoeeView, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12))
                        .addComponent(lblTerminateEmployeeError, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputIDTerminateEmployee, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTerminateEmployeeID, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlTerminateEmployeeInputLayout.setVerticalGroup(
            pnlTerminateEmployeeInputLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlTerminateEmployeeInputLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTerminateEmployeeID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputIDTerminateEmployee, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(lblTerminateEmployeeError, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTerminateEmplyoeeView)
                .addContainerGap())
        );

        pnlTerminateEmployeeResults.setBackground(new Color(204, 204, 204));
        pnlTerminateEmployeeResults.setBorder(BorderFactory.createEtchedBorder());

        lblTerminateEmployeeName.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblTerminateEmployeeName.setForeground(new Color(51, 51, 51));
        lblTerminateEmployeeName.setText("Name");

        lblTerminateEmployeeEmail.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblTerminateEmployeeEmail.setForeground(new Color(51, 51, 51));
        lblTerminateEmployeeEmail.setText("Email");

        lblTerminateEmployeeDate.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblTerminateEmployeeDate.setForeground(new Color(51, 51, 51));
        lblTerminateEmployeeDate.setText("Hire Date");

        lblTerminateEmployeeRole.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblTerminateEmployeeRole.setForeground(new Color(51, 51, 51));
        lblTerminateEmployeeRole.setText("Role");

        lblTerminateEmployeeDepartment.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblTerminateEmployeeDepartment.setForeground(new Color(51, 51, 51));
        lblTerminateEmployeeDepartment.setText("Department");

        lblTerminateEmployeeAccess.setFont(new Font("Candara", 0, 14)); // NOI18N
        lblTerminateEmployeeAccess.setForeground(new Color(51, 51, 51));
        lblTerminateEmployeeAccess.setText("Access Level");

        textTerminateEmployeeName.setEditable(false);
        textTerminateEmployeeName.setBackground(new Color(225, 225, 225));
        textTerminateEmployeeName.setFont(new Font("Candara", 0, 12)); // NOI18N
        textTerminateEmployeeName.setText("John Doe");
        textTerminateEmployeeName.setFocusable(false);

        textTerminateEmployeeEmail.setEditable(false);
        textTerminateEmployeeEmail.setBackground(new Color(225, 225, 225));
        textTerminateEmployeeEmail.setFont(new Font("Candara", 0, 12)); // NOI18N
        textTerminateEmployeeEmail.setText("jdoe555@email.com");
        textTerminateEmployeeEmail.setFocusable(false);

        textTerminateEmployeeDate.setEditable(false);
        textTerminateEmployeeDate.setBackground(new Color(225, 225, 225));
        textTerminateEmployeeDate.setFont(new Font("Candara", 0, 12)); // NOI18N
        textTerminateEmployeeDate.setText("12-31-1999");
        textTerminateEmployeeDate.setFocusable(false);

        textTerminateEmployeeRole.setEditable(false);
        textTerminateEmployeeRole.setBackground(new Color(225, 225, 225));
        textTerminateEmployeeRole.setFont(new Font("Candara", 0, 12)); // NOI18N
        textTerminateEmployeeRole.setText("Worker");
        textTerminateEmployeeRole.setFocusable(false);

        textTerminateEmployeeDepartment.setEditable(false);
        textTerminateEmployeeDepartment.setBackground(new Color(225, 225, 225));
        textTerminateEmployeeDepartment.setFont(new Font("Candara", 0, 12)); // NOI18N
        textTerminateEmployeeDepartment.setText("Maintenance");
        textTerminateEmployeeDepartment.setFocusable(false);

        textTerminateEmployeeAccess.setEditable(false);
        textTerminateEmployeeAccess.setBackground(new Color(225, 225, 225));
        textTerminateEmployeeAccess.setFont(new Font("Candara", 0, 12)); // NOI18N
        textTerminateEmployeeAccess.setText("1");
        textTerminateEmployeeAccess.setFocusable(false);

        btnTerminateEmplyoeeSubmit.setFont(new Font("Candara", 0, 14)); // NOI18N
        btnTerminateEmplyoeeSubmit.setText("Submit");
        btnTerminateEmplyoeeSubmit.addActionListener(this::btnTerminateEmployeeSubmitActionPerformed);

        GroupLayout pnlTerminateEmployeeResultsLayout = new GroupLayout(pnlTerminateEmployeeResults);
        pnlTerminateEmployeeResults.setLayout(pnlTerminateEmployeeResultsLayout);
        pnlTerminateEmployeeResultsLayout.setHorizontalGroup(
            pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlTerminateEmployeeResultsLayout.createSequentialGroup()
                .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTerminateEmployeeResultsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTerminateEmployeeEmail, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTerminateEmployeeName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTerminateEmployeeDate, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblTerminateEmployeeRole, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblTerminateEmployeeDepartment, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblTerminateEmployeeAccess, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(textTerminateEmployeeName, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTerminateEmployeeEmail, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTerminateEmployeeDate, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTerminateEmployeeRole, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTerminateEmployeeDepartment, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTerminateEmployeeAccess, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTerminateEmployeeResultsLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnTerminateEmplyoeeSubmit, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlTerminateEmployeeResultsLayout.setVerticalGroup(
            pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlTerminateEmployeeResultsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerminateEmployeeName)
                    .addComponent(textTerminateEmployeeName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerminateEmployeeEmail)
                    .addComponent(textTerminateEmployeeEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textTerminateEmployeeDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTerminateEmployeeDate))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textTerminateEmployeeRole, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTerminateEmployeeRole))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(textTerminateEmployeeDepartment, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTerminateEmployeeDepartment))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTerminateEmployeeResultsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerminateEmployeeAccess)
                    .addComponent(textTerminateEmployeeAccess, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTerminateEmplyoeeSubmit)
                .addContainerGap())
        );

        GroupLayout panelTerminateEmployeeLayout = new GroupLayout(panelTerminateEmployee);
        panelTerminateEmployee.setLayout(panelTerminateEmployeeLayout);
        panelTerminateEmployeeLayout.setHorizontalGroup(
            panelTerminateEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelTerminateEmployeeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlTerminateEmployeeInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(pnlTerminateEmployeeResults, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelTerminateEmployeeLayout.setVerticalGroup(
            panelTerminateEmployeeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelTerminateEmployeeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelTerminateEmployeeLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTerminateEmployeeResults, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTerminateEmployeeInput, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        tabPaneEmployeeSupervision.addTab("Terminate Employee", panelTerminateEmployee);

        GroupLayout pnlEmployeeOptionsLayout = new GroupLayout(pnlEmployeeOptions);
        pnlEmployeeOptions.setLayout(pnlEmployeeOptionsLayout);
        pnlEmployeeOptionsLayout.setHorizontalGroup(
            pnlEmployeeOptionsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeOptionsLayout.createSequentialGroup()
                .addComponent(tabPaneEmployeeSupervision, GroupLayout.PREFERRED_SIZE, 529, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEmployeeOptionsLayout.setVerticalGroup(
            pnlEmployeeOptionsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeOptionsLayout.createSequentialGroup()
                .addComponent(tabPaneEmployeeSupervision, GroupLayout.PREFERRED_SIZE, 329, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        GroupLayout pnlEmployeesLayout = new GroupLayout(pnlEmployees);
        pnlEmployees.setLayout(pnlEmployeesLayout);
        pnlEmployeesLayout.setHorizontalGroup(
            pnlEmployeesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnlEmployeesLayout.createSequentialGroup()
                .addComponent(pnlEmployeeOptions, GroupLayout.PREFERRED_SIZE, 510, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlEmployeesLayout.setVerticalGroup(
            pnlEmployeesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEmployeeOptions, GroupLayout.PREFERRED_SIZE, 322, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlEmployees, GroupLayout.PREFERRED_SIZE, 510, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlEmployees, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void btnViewEmployeeSubmitActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int employeeID = Integer.parseInt(inputIDViewEmployee.getText());
            Employee emp = employeeService.getEmployeeByID(employeeID);
            
            textViewEmployeeName.setText(emp.getFirstName() + " " + emp.getLastName());
            textViewEmployeeEmail.setText(emp.getFirstName().toLowerCase() + "." + emp.getLastName().toLowerCase() + "@company.com");
            textViewEmployeeDate.setText(emp.getHireDate().toString());
            textViewEmployeeRole.setText(emp.getRole());
            textViewEmployeeDepartment.setText(emp.getDepartment());
            textViewEmployeeAccess.setText(String.valueOf(emp.getAccessLevel()));
        } catch (NumberFormatException e) {
            lblViewEmployeeError.setText("Invalid Employee ID");
        }
    }                                                     

    private void btnHireEmployeeSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            String name = textHireEmployeeName.getText();
            String[] nameParts = name.split(" ");
            String firstName = nameParts.length > 0 ? nameParts[0] : "";
            String lastName = nameParts.length > 1 ? nameParts[1] : "";
            String role = textHireEmployeeRole.getText();
            String department = textHireEmployeeDepartment.getText();
            int accessLevel = Integer.parseInt(textHireEmployeeAccess.getText());
            
            Employee emp = new Employee(0, firstName, lastName, new java.util.Date(), true, 
                                       role, accessLevel, department, new java.util.ArrayList<>());
            int reportID = employeeService.employeeHired(emp);
            
            txtHireEmployeeResult.setText("Employee hired successfully!\nReport ID: " + reportID);
        } catch (Exception e) {
            txtHireEmployeeResult.setText("Error: " + e.getMessage());
        }
    }                                                     

    private void btnTerminateEmployeeViewActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int employeeID = Integer.parseInt(inputIDTerminateEmployee.getText());
            Employee emp = employeeService.getEmployeeByID(employeeID);
            
            textTerminateEmployeeName.setText(emp.getFirstName() + " " + emp.getLastName());
            textTerminateEmployeeEmail.setText(emp.getFirstName().toLowerCase() + "." + emp.getLastName().toLowerCase() + "@company.com");
            textTerminateEmployeeDate.setText(emp.getHireDate().toString());
            textTerminateEmployeeRole.setText(emp.getRole());
            textTerminateEmployeeDepartment.setText(emp.getDepartment());
            textTerminateEmployeeAccess.setText(String.valueOf(emp.getAccessLevel()));
        } catch (NumberFormatException e) {
            lblTerminateEmployeeError.setText("Invalid Employee ID");
        }
    }                                                        

    private void btnTerminateEmployeeSubmitActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int employeeID = Integer.parseInt(inputIDTerminateEmployee.getText());
            Employee emp = employeeService.getEmployeeByID(employeeID);
            emp.setActiveEmployee(false);
            int reportID = employeeService.employeeFired(emp);
            
            lblTerminateEmployeeError.setText("Employee terminated. Report ID: " + reportID);
        } catch (NumberFormatException e) {
            lblTerminateEmployeeError.setText("Invalid Employee ID");
        }
    }                                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnHireEmployeeSubmit;
    private javax.swing.JButton btnTerminateEmplyoeeSubmit;
    private javax.swing.JButton btnTerminateEmplyoeeView;
    private javax.swing.JButton btnViewEmplyoeeSubmit;
    private javax.swing.JTextField inputIDTerminateEmployee;
    private javax.swing.JTextField inputIDViewEmployee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHireEmployeeAccess;
    private javax.swing.JLabel lblHireEmployeeDepartment;
    private javax.swing.JLabel lblHireEmployeeEmail;
    private javax.swing.JLabel lblHireEmployeeName;
    private javax.swing.JLabel lblHireEmployeeRole;
    private javax.swing.JLabel lblTerminateEmployeeAccess;
    private javax.swing.JLabel lblTerminateEmployeeDate;
    private javax.swing.JLabel lblTerminateEmployeeDepartment;
    private javax.swing.JLabel lblTerminateEmployeeEmail;
    private javax.swing.JLabel lblTerminateEmployeeError;
    private javax.swing.JLabel lblTerminateEmployeeID;
    private javax.swing.JLabel lblTerminateEmployeeName;
    private javax.swing.JLabel lblTerminateEmployeeRole;
    private javax.swing.JLabel lblViewEmployeeAccess;
    private javax.swing.JLabel lblViewEmployeeDate;
    private javax.swing.JLabel lblViewEmployeeDepartment;
    private javax.swing.JLabel lblViewEmployeeEmail;
    private javax.swing.JLabel lblViewEmployeeError;
    private javax.swing.JLabel lblViewEmployeeID;
    private javax.swing.JLabel lblViewEmployeeName;
    private javax.swing.JLabel lblViewEmployeeRole;
    private javax.swing.JPanel panelHireEmployee;
    private javax.swing.JPanel panelTerminateEmployee;
    private javax.swing.JPanel panelViewEmployee;
    private javax.swing.JPanel pnlEmployeeOptions;
    private javax.swing.JPanel pnlEmployees;
    private javax.swing.JPanel pnlHireEmployee;
    private javax.swing.JPanel pnlTerminateEmployeeInput;
    private javax.swing.JPanel pnlTerminateEmployeeResults;
    private javax.swing.JPanel pnlViewEmployeeInput;
    private javax.swing.JPanel pnlViewEmployeeResults;
    private javax.swing.JTabbedPane tabPaneEmployeeSupervision;
    private javax.swing.JTextField textHireEmployeeAccess;
    private javax.swing.JTextField textHireEmployeeDepartment;
    private javax.swing.JTextField textHireEmployeeEmail;
    private javax.swing.JTextField textHireEmployeeName;
    private javax.swing.JTextField textHireEmployeeRole;
    private javax.swing.JTextField textTerminateEmployeeAccess;
    private javax.swing.JTextField textTerminateEmployeeDate;
    private javax.swing.JTextField textTerminateEmployeeDepartment;
    private javax.swing.JTextField textTerminateEmployeeEmail;
    private javax.swing.JTextField textTerminateEmployeeName;
    private javax.swing.JTextField textTerminateEmployeeRole;
    private javax.swing.JTextField textViewEmployeeAccess;
    private javax.swing.JTextField textViewEmployeeDate;
    private javax.swing.JTextField textViewEmployeeDepartment;
    private javax.swing.JTextField textViewEmployeeEmail;
    private javax.swing.JTextField textViewEmployeeName;
    private javax.swing.JTextField textViewEmployeeRole;
    private javax.swing.JTextArea txtHireEmployeeResult;
    // End of variables declaration                   
}
