/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.devry.ecsproject.BusinessLayer;

/**
 *
 * @author Jordan
 */
public class ReportsGUI extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePanel
     */
    public ReportsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlReports = new javax.swing.JPanel();
        tabPaneReportsOptions = new javax.swing.JTabbedPane();
        pnlGenerateReport = new javax.swing.JPanel();
        btnGenerateEquipmentReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReportOutput = new javax.swing.JTextArea();
        pnlCreateReportTemplate = new javax.swing.JPanel();

        pnlReports.setBackground(new java.awt.Color(204, 204, 204));

        pnlGenerateReport.setBackground(new java.awt.Color(204, 204, 204));
        
        btnGenerateEquipmentReport.setText("Generate Equipment Report");
        btnGenerateEquipmentReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateEquipmentReportActionPerformed(evt);
            }
        });
        
        txtReportOutput.setColumns(20);
        txtReportOutput.setRows(5);
        txtReportOutput.setEditable(false);
        jScrollPane1.setViewportView(txtReportOutput);

        javax.swing.GroupLayout pnlGenerateReportLayout = new javax.swing.GroupLayout(pnlGenerateReport);
        pnlGenerateReport.setLayout(pnlGenerateReportLayout);
        pnlGenerateReportLayout.setHorizontalGroup(
            pnlGenerateReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenerateReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGenerateReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(btnGenerateEquipmentReport))
                .addContainerGap())
        );
        pnlGenerateReportLayout.setVerticalGroup(
            pnlGenerateReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenerateReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerateEquipmentReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPaneReportsOptions.addTab("Generate Report", pnlGenerateReport);

        pnlCreateReportTemplate.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlCreateReportTemplateLayout = new javax.swing.GroupLayout(pnlCreateReportTemplate);
        pnlCreateReportTemplate.setLayout(pnlCreateReportTemplateLayout);
        pnlCreateReportTemplateLayout.setHorizontalGroup(
            pnlCreateReportTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        pnlCreateReportTemplateLayout.setVerticalGroup(
            pnlCreateReportTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        tabPaneReportsOptions.addTab("Create Template", pnlCreateReportTemplate);

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsLayout.createSequentialGroup()
                .addComponent(tabPaneReportsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneReportsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlReports, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void btnGenerateEquipmentReportActionPerformed(java.awt.event.ActionEvent evt) {
        java.util.List<String> transactions = EquipmentGUIService.getTransactionLog();
        
        if (transactions.isEmpty()) {
            txtReportOutput.setText("No transactions recorded yet.");
        } else {
            StringBuilder report = new StringBuilder();
            report.append("=== EQUIPMENT TRANSACTION REPORT ===\n\n");
            report.append("Total Transactions: ").append(transactions.size()).append("\n\n");
            
            for (int i = 0; i < transactions.size(); i++) {
                report.append((i + 1)).append(". ").append(transactions.get(i)).append("\n");
            }
            
            txtReportOutput.setText(report.toString());
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnGenerateEquipmentReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCreateReportTemplate;
    private javax.swing.JPanel pnlGenerateReport;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JTabbedPane tabPaneReportsOptions;
    private javax.swing.JTextArea txtReportOutput;
    // End of variables declaration                   
}
